# Generated by Django 5.0.3 on 2024-05-01 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_product',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
